import mongoose, { Schema } from "mongoose";
import { THREAD_TYPE, MESSAGE_TYPE } from "@/lib/constants";

/**
 * Thread
 *
 * A conversation channel inside a house. Every house gets a 'general'
 * thread on creation. Managers and members can create custom threads.
 *
 * Free plan: 1 thread (general only)
 * Pro plan: unlimited threads
 */
const ThreadSchema = new Schema(
  {
    houseId: {
      type: Schema.Types.ObjectId,
      ref: "House",
      required: true,
      index: true,
    },
    createdBy: {
      type: Schema.Types.ObjectId,
      ref: "User",
      required: true,
    },

    name: {
      type: String,
      required: true,
      trim: true,
      maxlength: 80,
    },
    type: {
      type: String,
      enum: Object.values(THREAD_TYPE),
      default: THREAD_TYPE.CUSTOM,
    },
    description: {
      type: String,
      maxlength: 200,
      default: "",
    },

    // ── Pinned message ────────────────────────────────────────────────────────
    pinnedMessageId: {
      type: Schema.Types.ObjectId,
      ref: "Message",
      default: null,
    },

    // ── Last message preview (denormalized for thread list UI) ────────────────
    lastMessageAt: { type: Date, default: null },
    lastMessageText: { type: String, default: "", maxlength: 200 },

    // ── Archive ───────────────────────────────────────────────────────────────
    isArchived: { type: Boolean, default: false },

    deletedAt: { type: Date, default: null },
  },
  { timestamps: true }
);

ThreadSchema.index({ houseId: 1, isArchived: 1 });
ThreadSchema.index({ houseId: 1, lastMessageAt: -1 });
ThreadSchema.index({ houseId: 1, type: 1 });

export const Thread =
  mongoose.models.Thread || mongoose.model("Thread", ThreadSchema);

// ─────────────────────────────────────────────────────────────────────────────
/**
 * Message
 *
 * A single message in a thread. Supports text, images, and system messages.
 * System messages are generated by the server for events like
 * "John marked rent as paid" or "New task assigned to Sarah".
 *
 * Messages are paginated (cursor-based, by createdAt desc) — never load all.
 */
const MessageSchema = new Schema(
  {
    threadId: {
      type: Schema.Types.ObjectId,
      ref: "Thread",
      required: true,
      index: true,
    },
    houseId: {
      type: Schema.Types.ObjectId,
      ref: "House",
      required: true,
      index: true, // denormalized for fast house-level queries
    },
    senderId: {
      type: Schema.Types.ObjectId,
      ref: "User",
      required: true,
    },

    type: {
      type: String,
      enum: Object.values(MESSAGE_TYPE),
      default: MESSAGE_TYPE.TEXT,
    },

    // ── Text content ──────────────────────────────────────────────────────────
    text: {
      type: String,
      maxlength: 2000,
      default: "",
    },

    // ── Media (image / file messages) ─────────────────────────────────────────
    mediaUrl: { type: String, default: null },
    mediaName: { type: String, default: null },
    mediaType: { type: String, default: null }, // MIME type

    // ── Mentions ──────────────────────────────────────────────────────────────
    mentions: [{ type: Schema.Types.ObjectId, ref: "User" }],

    // ── Read receipts ─────────────────────────────────────────────────────────
    // Array of userIds who have read this message
    readBy: [{ type: Schema.Types.ObjectId, ref: "User" }],

    // ── Reply threading ───────────────────────────────────────────────────────
    replyTo: {
      type: Schema.Types.ObjectId,
      ref: "Message",
      default: null,
    },

    // ── Soft delete ───────────────────────────────────────────────────────────
    deletedAt: { type: Date, default: null },
  },
  { timestamps: true }
);

// ── Indexes ───────────────────────────────────────────────────────────────────
// Cursor-based pagination: fetch messages for a thread, newest first
MessageSchema.index({ threadId: 1, createdAt: -1 });
MessageSchema.index({ houseId: 1, createdAt: -1 });
// Fast mention lookup
MessageSchema.index({ mentions: 1, createdAt: -1 });

export const Message =
  mongoose.models.Message || mongoose.model("Message", MessageSchema);
